"use client";

import { useCallback, useEffect, useState } from "react";
import { compareRole } from "../../lib/api";
import type { RoleComparison } from "../../lib/types";
import { li } from "../../lib/theme";
import FitRing from "./FitRing";
import SkillColumns from "./SkillColumns";

export default function ComparisonPanel({ userId, roleId, onBuildPath }: { userId: string; roleId: string; onBuildPath: () => void }) {
  const [comparison, setComparison] = useState<RoleComparison | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(() => { let active = true; setLoading(true); setError(false); compareRole({ userId, roleId }).then((value) => { if (active) setComparison(value); }).catch(() => { if (active) setError(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [userId, roleId]);
  useEffect(() => load(), [load]);
  if (error) return <section style={{ ...card, padding: 32 }}><p>We couldn’t load this role comparison.</p><button onClick={load} style={primary}>Retry</button></section>;
  if (loading || !comparison) return <section style={{ ...card, padding: 32, color: li.textSecondary }}>Loading role fit…</section>;
  const { role, readinessScore, strengths, skillGaps, aggregateAnalysis } = comparison; const missing = skillGaps.filter((gap) => gap.status === "missing").map((gap) => gap.skill);
  return <section style={card}><div style={{ height: 88, background: `linear-gradient(120deg, ${li.blue}, #378fe9)` }} /><div style={{ padding: "0 24px 24px" }}><div style={{ marginTop: -24 }}><div style={{ width: 72, height: 72, borderRadius: 12, background: li.blueLight, border: `2px solid ${li.cardBg}`, boxShadow: li.cardShadow, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 30, fontWeight: 700, color: li.blue }}>{role.name.charAt(0)}</div><h1 style={{ margin: "12px 0 4px", fontSize: 24, overflowWrap: "anywhere" }}>{role.name}</h1><p style={{ margin: 0, color: li.textSecondary, lineHeight: 1.5 }}>{role.summary}</p><div style={{ marginTop: 12, padding: "12px 16px", background: li.pageBg, borderRadius: li.cardRadius, fontSize: 14, lineHeight: 1.45 }}><strong>{aggregateAnalysis.analyzed.toLocaleString()} profiles analyzed.</strong> {aggregateAnalysis.landed.toLocaleString()} held this role; {aggregateAnalysis.similar.toLocaleString()} share at least one skill with you.</div></div><Divider /><div style={{ display: "flex", gap: 32, alignItems: "center", marginBottom: 20, flexWrap: "wrap" }}><FitRing percent={readinessScore} /><div style={{ flex: 1, minWidth: "min(100%, 240px)" }}><h2 style={{ margin: "0 0 10px", fontSize: 16 }}>Open roles <span style={{ color: li.textSecondary, fontWeight: 400 }}>· {role.jobCount} listed</span></h2>{role.postings?.map((posting, index, all) => <article key={posting.id} style={{ display: "flex", gap: 12, padding: "10px 0", borderBottom: index < all.length - 1 ? `1px solid ${li.cardBorder}` : "none" }}><div style={{ width: 40, height: 40, borderRadius: 6, background: li.blueLight, color: li.blue, display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, flexShrink: 0 }}>{posting.company.charAt(0)}</div><div style={{ minWidth: 0 }}><strong style={{ color: li.blue, fontSize: 15 }}>{role.name}</strong><div style={{ color: li.textSecondary, fontSize: 14 }}>{posting.company} · {posting.location}</div><div style={{ color: li.textHint, fontSize: 12, marginTop: 4 }}>{posting.level} · ${Math.round(posting.salaryFrom / 1000)}K–${Math.round(posting.salaryTo / 1000)}K{posting.easyApply ? " · Easy Apply" : ""}</div></div></article>)}</div></div><Divider /><SkillColumns haveSkills={strengths} missingSkills={missing} /><button onClick={onBuildPath} style={{ ...primary, marginTop: 24, padding: "10px 28px", fontSize: 16 }}>Build my path →</button></div></section>;
}
const card: React.CSSProperties = { background: li.cardBg, borderRadius: li.cardRadius, boxShadow: li.cardShadow, fontFamily: li.font, color: li.textPrimary, overflow: "hidden", width: "min(100%, 760px)", margin: "0 auto" };
const primary: React.CSSProperties = { background: li.blue, color: "#fff", border: "none", borderRadius: 24, padding: "8px 20px", fontWeight: 600, cursor: "pointer", fontFamily: li.font };
function Divider() { return <hr style={{ border: "none", borderTop: `1px solid ${li.cardBorder}`, margin: "20px 0" }} />; }
