"use client";

import { useCallback, useEffect, useState } from "react";
import { generatePath, getOpportunities } from "../../lib/api";
import { loadProgress, saveProgress } from "../../lib/persistence";
import type { OpportunityMatch, PersonalizedPath } from "../../lib/types";
import { li } from "../../lib/theme";

type Milestone = PersonalizedPath["milestones"][number];
function phaseFor(order: number) { return order === 1 ? "Next 4 weeks" : order <= 3 ? "This quarter" : "Next 6 months"; }
function targetFor(date: string, order: number) { const d = new Date(date); d.setDate(d.getDate() + (order === 1 ? 28 : order <= 3 ? 90 : 180)); return `Target by ${d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`; }

export default function MilestoneView({ userId, roleId }: { userId: string; roleId: string }) {
  const [path, setPath] = useState<PersonalizedPath | null>(null); const [opportunities, setOpportunities] = useState<OpportunityMatch[] | null>(null);
  const [pathError, setPathError] = useState(false); const [opportunityError, setOpportunityError] = useState(false);
  const [completed, setCompleted] = useState<number[]>([]); const [checkedAt, setCheckedAt] = useState<string | null>(null);
  const loadPath = useCallback(() => { setPathError(false); generatePath({ userId, roleId }).then(setPath).catch(() => setPathError(true)); }, [userId, roleId]);
  const loadOpportunities = useCallback(() => { setOpportunityError(false); getOpportunities({ userId, limit: 12 }).then((r) => setOpportunities(r.opportunities)).catch(() => setOpportunityError(true)); }, [userId]);
  useEffect(() => { const p = loadProgress(userId, roleId); setCompleted(p.completedOrders); setCheckedAt(p.lastCheckedAt); loadPath(); loadOpportunities(); }, [userId, roleId, loadPath, loadOpportunities]);
  function toggle(order: number) { const next = completed.includes(order) ? completed.filter((v) => v !== order) : [...completed, order]; const now = new Date().toISOString(); setCompleted(next); setCheckedAt(now); saveProgress(userId, roleId, { completedOrders: next, lastCheckedAt: now }); }
  if (pathError) return <Notice text="We couldn’t build your path." onRetry={loadPath} />;
  if (!path) return <section style={panel}>Building your next steps...</section>;
  const active = path.milestones.filter((m) => !completed.includes(m.order)); const done = path.milestones.filter((m) => completed.includes(m.order)); const percent = Math.round((done.length / path.milestones.length) * 100);
  return <section style={{ display: "grid", gap: 16, fontFamily: li.font }}>
    <div style={panel}><p style={{ margin: 0, color: li.green, fontSize: 12, fontWeight: 700, textTransform: "uppercase" }}>Your path</p><h2 style={{ margin: "4px 0", color: li.textPrimary }}>Progress toward {path.role.name}</h2><p style={{ color: li.textSecondary }}>{path.skillGaps.filter((g) => g.status === "missing").length ? `${path.skillGaps.filter((g) => g.status === "missing").length} skill${path.skillGaps.filter((g) => g.status === "missing").length === 1 ? "" : "s"} separate you from this role today.` : "Your profile already covers the role's core skill set."} {done.length} of {path.milestones.length} actions complete · {path.readinessScore}% role readiness</p><div style={{ height: 10, background: li.cardBorder, borderRadius: 8, overflow: "hidden" }}><div style={{ height: "100%", width: `${percent}%`, background: li.green, transition: "width .25s ease" }} /></div><p style={{ marginBottom: 0, fontSize: 12, color: li.textHint }}>{checkedAt ? `Last check-in ${new Date(checkedAt).toLocaleDateString()}` : "Check off actions as you complete them."}</p></div>
    <div style={panel}><h3 style={{ marginTop: 0 }}>Timeline</h3>{["Next 4 weeks", "This quarter", "Next 6 months"].map((phase) => { const items = active.filter((m) => phaseFor(m.order) === phase); return items.length ? <div key={phase}><p style={{ color: li.blue, fontSize: 13, fontWeight: 700, margin: "18px 0 6px" }}>{phase}</p>{items.map((m) => <MilestoneItem key={m.order} milestone={m} checked={false} target={targetFor(path.generatedAt, m.order)} onToggle={() => toggle(m.order)} />)}</div> : null; })}</div>
    {done.length > 0 && <div style={panel}><h3 style={{ marginTop: 0 }}>Completed</h3>{done.map((m) => <MilestoneItem key={m.order} milestone={m} checked target="Completed" onToggle={() => toggle(m.order)} />)}</div>}
    <div style={panel}><h3 style={{ marginTop: 0 }}>Opportunities to explore</h3><p style={{ fontSize: 12, color: li.textHint }}>Named examples only — verify availability and eligibility.</p>{opportunityError ? <Notice text="We couldn’t load opportunities." onRetry={loadOpportunities} /> : opportunities === null ? <p style={{ color: li.textSecondary }}>Finding examples that fit your strengths…</p> : <div style={{ display: "flex", gap: 12, overflowX: "auto" }}>{opportunities.map((o) => <article key={o.id} style={{ flex: "0 0 230px", border: `1px solid ${li.cardBorder}`, borderRadius: 10, padding: 14 }}><strong>{o.name}</strong><p style={{ margin: "5px 0", fontSize: 13, color: li.textSecondary }}>{o.organization} · {o.type}</p><p style={{ margin: "5px 0", fontSize: 13 }}>{o.fit}% skill overlap</p><p style={{ margin: 0, fontSize: 12, color: li.textHint }}>{o.matchedSkills.join(", ") || "A new direction to explore"}</p></article>)}</div>}</div>
    <p style={{ margin: 0, color: li.textHint, fontSize: 12, fontStyle: "italic" }}>{path.disclaimer}</p>
  </section>;
}
const panel: React.CSSProperties = { background: li.cardBg, borderRadius: li.cardRadius, boxShadow: li.cardShadow, padding: "20px 24px" };
function Notice({ text, onRetry }: { text: string; onRetry: () => void }) { return <section style={panel}><p>{text}</p><button onClick={onRetry} style={{ background: li.blue, color: "#fff", border: "none", borderRadius: 20, padding: "8px 16px", cursor: "pointer" }}>Retry</button></section>; }
function MilestoneItem({ milestone, checked, target, onToggle }: { milestone: Milestone; checked: boolean; target: string; onToggle: () => void }) { return <article style={{ borderTop: `1px solid ${li.cardBorder}`, padding: "14px 0", display: "flex", gap: 12 }}><input type="checkbox" checked={checked} onChange={onToggle} aria-label={`Mark ${milestone.title} complete`} style={{ marginTop: 4, accentColor: li.blue }} /><div><strong>{milestone.title}</strong><div style={{ fontSize: 12, color: li.textHint }}>{target} · <span>{milestone.course?.name || milestone.targetSkill}</span></div><div style={{ fontSize: 12, color: li.textHint }}>{milestone.targetSkill}</div><p style={{ margin: "5px 0", fontSize: 13, color: li.textSecondary }}>{milestone.reason}</p><ul style={{ margin: 0, paddingLeft: 18, fontSize: 13, color: li.textSecondary }}><li>{milestone.project}</li><li>{milestone.networkingAction}</li><li>{milestone.profileCheckpoint}</li></ul></div></article>; }
