// Shared data contract between backend (/api) and the Comparison Page.
// Mirrors what backend/build_data.py produces from the real sample_data/ files
// (frontend/data/*.json is generated by backend/precompute.py) and backend/fit.py.

// A real job posting pulled from jobs_data.json.
export interface Posting {
  id: string;
  company: string;
  location: string;
  level: string;
  salaryFrom: number;
  salaryTo: number;
  easyApply: boolean; // REAL flag from jobs_data.json
}

export interface Role {
  id: string;
  name: string;
  category?: string;
  description: string;
  skills: string[];
  companies: string[];
  // Real fields derived from jobs_data.json by precompute.py:
  industries?: string[];
  levels?: string[];
  salaryFrom?: number;
  salaryTo?: number;
  easyApplyPct?: number;
  jobCount?: number;
  postings?: Posting[];
}

// The single logged-in profile ("you").
export interface User {
  id: string;
  name: string;
  degree?: string;
  skills: string[];
}

// A real person from the database who landed a role and matches your profile.
// The numeric person-to-person overlap stays internal; we expose a label +
// the skills you share with them.
export interface MatchedPerson {
  id: string;
  name: string;
  degree?: string;
  sharedSkills: string[];
  matchLabel: string; // "Strong match" | "Good match" | "Some overlap"
}

// A real course pulled from course_data.json (for the gap / Milestone page).
export interface Course {
  id: string;
  name: string;
  length?: { value: number; unit: string };
  level?: string;
}

// Returned by GET /api/fit and by the client-side fallback (lib/fit.ts).
// Carries the real role enrichment so the panel can render salary, real
// postings, and the real easy-apply flag.
export interface FitResult {
  role: Pick<
    Role,
    | "id"
    | "name"
    | "description"
    | "companies"
    | "salaryFrom"
    | "salaryTo"
    | "easyApplyPct"
    | "jobCount"
    | "postings"
  >;
  percent: number; // 0-100
  haveSkills: string[];
  missingSkills: string[];
  // Real people who landed this role and best match your profile.
  matches: MatchedPerson[];
}
